### ISSUE TITLE
Make microsandbox more micro

### ISSUE THREAD

**Issue by frc4533-lincoln** [microsandbox/microsandbox#243]
Found this project yesterday and very excited to start tinkering with it.
Working on a PR for Alpine/musl libc support, but have some time to kill while the kernel builds :)

I don't mean to offend but as security is a major selling point, microsandbox has too many dependencies.

 - Async methods in traits were stabilized a few Rust versions back, so `async-trait` isn't needed anymore
 - There's many redundant dependencies:
   - `psutil` (used once) and `sysinfo` (never used)
   - `tokio-stream` (never used) and `async-stream` (also never used)
   - `typed-builder` (used 7 times) and `bon` (never used)
   - `pin-project` (never used) and `pin-project-lite` (also never used)
 - Some additional unused dependencies:
   - `dotenvy`
   - `structstruck`
   - `file-lock`
   - `tracing-appender`
   - `crossterm`
   - `async-recursion`
   - `signal-hook`
   - `scopeguard`
 - `toml` is imported, but only used in an error definition

And last does it absolutely have to be YAML?
Could it not be TOML?

**Comment by appcypher** [comment]
> Found this project yesterday and very excited to start tinkering with it.

Thank you. Welcome!

> I don't mean to offend but as security is a major selling point

Definitely appreciate the feedback

> microsandbox has too many dependencies

Fixing that now. As you probably already seen, the tests, checks, CI are not where I want them to be yet.

> Could it not be TOML

Tried TOML early on. It was weird. It writes nice for Cargo but not microsandbox. It is verbose and can get unuintuitive sometimes. I'm avoiding any friction and devops eng are already familiar with Yaml. Yaml seems easier to write and read IMO.

I have also considered Strict Yaml, but I can't find an actively maintained one. And I have even tried supporting both but that is just a terrible idea.

Anyway. There is still time to change. Which would you prefer?

```yaml
sandboxes:
  api:
    version: "1.0.0"
    image: "python:3.11-slim"
    meta:
      description: "A simple API"
    ram: 1024
    cpus: 1
    volumes:
      - "./api:/app/src"
    ports:
      - "8000:8000"
    envs:
      - "DEBUG=false"
      - "API_PORT=8000"
      - "PYTHONPATH=/app/packages"
    depends_on:
      - "database"
      - "cache"
    workdir: "/app"
    shell: "/bin/bash"
    scripts:
      start: "PYTHONPATH=/app/packages python -m uvicorn src.main:app --host 0.0.0.0 --port 8000"
      test: "PYTHONPATH=/app/packages pytest src/tests/"
    scope: "public"
    imports:
      api_base:
        packages: "/app/packages"
```

```toml
[sandboxes.api]
version = "1.0.0"
image = "python:3.11-slim"
ram = 1024
cpus = 1
workdir = "/app"
shell = "/bin/bash"
scope = "public"
volumes = ["./api:/app/src"]
ports = ["8000:8000"]
envs = ["DEBUG=false", "API_PORT=8000", "PYTHONPATH=/app/packages"]
depends_on = ["database", "cache"]

[sandboxes.api.meta]
description = "A simple API"

[sandboxes.api.scripts]
start = "PYTHONPATH=/app/packages python -m uvicorn src.main:app --host 0.0.0.0 --port 8000"
test = "PYTHONPATH=/app/packages pytest src/tests/"

[sandboxes.api.imports]
api_base = { packages = "/app/packages" }
```
