### ISSUE TITLE
Yaml, Toml or Both

### ISSUE THREAD

**Issue by appcypher** [microsandbox/microsandbox#259]
@frc4533-lincoln raised the issue of which config format to choose [here](https://github.com/microsandbox/microsandbox/issues/243).

Personally, I've also been conflicted about which format to use, so I'm opening it up here for discussion.

It's still early days, making this the ideal time to shape the direction of our config format.

---

### YAML

```yaml
sandboxes:
  api:
    version: "1.0.0"
    image: "python:3.11-slim"
    meta:
      description: "A simple API"
    ram: 1024
    cpus: 1
    volumes:
      - "./api:/app/src"
    ports:
      - "8000:8000"
    envs:
      - "DEBUG=false"
      - "API_PORT=8000"
      - "PYTHONPATH=/app/packages"
    depends_on:
      - "database"
      - "cache"
    workdir: "/app"
    shell: "/bin/bash"
    scripts:
      start: "PYTHONPATH=/app/packages python -m uvicorn src.main:app --host 0.0.0.0 --port 8000"
      test: "PYTHONPATH=/app/packages pytest src/tests/"
    scope: "public"
    imports:
      api_base:
        packages: "/app/packages"
```

### TOML

```toml
[sandboxes.api]
version = "1.0.0"
image = "python:3.11-slim"
ram = 1024
cpus = 1
workdir = "/app"
shell = "/bin/bash"
scope = "public"
volumes = ["./api:/app/src"]
ports = ["8000:8000"]
envs = ["DEBUG=false", "API_PORT=8000", "PYTHONPATH=/app/packages"]
depends_on = ["database", "cache"]

[sandboxes.api.meta]
description = "A simple API"

[sandboxes.api.scripts]
start = "PYTHONPATH=/app/packages python -m uvicorn src.main:app --host 0.0.0.0 --port 8000"
test = "PYTHONPATH=/app/packages pytest src/tests/"

[sandboxes.api.imports]
api_base = { packages = "/app/packages" }
```
